name: 'Feishu Bot Hook'
description: ''
inputs:
  github-token:
    description: 'Github Token'
    required: true
  job-type:
    description: 'Job Type'
    default: 'PullRequest'
  job-status:
    description: 'Job Status'
    default: ''
  hook-id:
    description: 'Feishu Hook ID'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: framely/actions-composite-expand@main
      with:
        main: |-
          URI="https://api.github.com"
          API_HEADER="Accept: application/vnd.github.v3+json"
          AUTH_HEADER="Authorization: token ${{ inputs.github-token }}"
          BODY=$(curl -sSL -H "${AUTH_HEADER}" -H "$API_HEADER" "$URI/repos/${GITHUB_REPOSITORY}/actions/runs/${{ github.run_id }}/jobs")
          WORKFLOW_URL=$(echo "$BODY" | jq .jobs | jq .[-1] | jq .html_url | sed 's/"//g')

          IS_PR=${{ github.event_name == 'pull_request' }}
          ICON=😀
          if [ $IS_PR == true ]; then
              TITLE="start ${{ github.repository }} pr  ${ICON}"
              URL=""https://github.com/${{ github.repository }}/pull/$(echo ${{ github.ref }} | awk -F '/' '{print $3}')
          else
              TITLE="start ${{ github.repository }} ${{ github.ref }}  ${ICON}"
              URL="https://github.com/${{ github.repository }}/tree/${{ github.ref_name }}"
          fi

          cat << EOF > data.txt
          {
              "msg_type": "post",
              "content": {
                  "post": {
                      "zh_cn": {
                          "title": "${TITLE}",
                          "content": [
                            [{"tag":"text", "text":"代码信息: "}, {"tag":"a", "text":"${URL}", "href":"${URL}"}],
                            [{"tag":"text", "text":"构建详情: "}, {"tag":"a", "text":"${WORKFLOW_URL}", "href":"${WORKFLOW_URL}"}]
                          ]
                      }
                  }
              }
          }
          EOF
          curl -H "Content-Type: application/json" -d @data.txt https://open.feishu.cn/open-apis/bot/v2/hook/${{ inputs.hook-id }}

        post: |-
          URI="https://api.github.com"
          API_HEADER="Accept: application/vnd.github.v3+json"
          AUTH_HEADER="Authorization: token ${{ inputs.github-token }}"
          BODY=$(curl -sSL -H "${AUTH_HEADER}" -H "$API_HEADER" "$URI/repos/${GITHUB_REPOSITORY}/actions/runs/${{ github.run_id }}/jobs")
          WORKFLOW_URL=$(echo "$BODY" | jq .jobs | jq .[-1] | jq .html_url | sed 's/"//g')

          IS_PR=${{ github.event_name == 'pull_request' }}
          if [ ${{ job.status }} == success ]; then
              ICON=✅
          elif [ ${{ job.status }} == failure ]; then
              ICON=❌
          else
              ICON=❓
          fi

          if [ $IS_PR == true ]; then
              TITLE="${{ job.status }} ${{ github.repository }} pr  ${ICON}"
              URL=""https://github.com/${{ github.repository }}/pull/$(echo ${{ github.ref }} | awk -F '/' '{print $3}')
          else
              TITLE="${{ job.status }} ${{ github.repository }} ${{ github.ref }}  ${ICON}"
              URL="https://github.com/${{ github.repository }}/tree/${{ github.ref_name }}"
          fi

          cat << EOF > data.txt
          {
              "msg_type": "post",
              "content": {
                  "post": {
                      "zh_cn": {
                          "title": "${TITLE}",
                          "content": [
                            [{"tag":"text", "text":"代码信息: "}, {"tag":"a", "text":"${URL}", "href":"${URL}"}],
                            [{"tag":"text", "text":"构建详情: "}, {"tag":"a", "text":"${WORKFLOW_URL}", "href":"${WORKFLOW_URL}"}]
                          ]
                      }
                  }
              }
          }
          EOF
          curl -H "Content-Type: application/json" -d @data.txt https://open.feishu.cn/open-apis/bot/v2/hook/${{ inputs.hook-id }}
